apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniform-wala-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uniform-wala
  template:
    metadata:
      labels:
        app: uniform-wala
    spec:
      containers:
      - name: flask-container
        image: uniform-wala:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
