pipeline {
    agent any
    trigger {
      githubPush()
      }
    stages {
      stage('cloning repo'){
        steps {
           git branch: 'master', 
                    url: 'https://github.com/kingpin1374/Codtech-internship-tasks.git', 
                    credentialsId: 'github'
        }
      }
        stage('Build Image') {
            steps {
                sh "docker build -t uniform-wala:local ."
            }
        }
        stage('Load into Kind') {
            steps {
                // This moves the image into the Kind cluster
                sh "kind load docker-image uniform-wala:local"
            }
        }
        stage('Deploy') {
            steps {
                sh "kubectl apply -f deployment.yaml"
                sh "kubectl apply -f service.yaml"
                sh "kubectl rollout status deployment/uniform-wala-app"
            }
        }
    }
}
