pipeline {
    agent any
  triggers{
      githubPush()
      }
    stages {
      stage('cloning repo'){
        steps {
           git branch: 'master', 
                    url: 'https://github.com/kingpin1374/Codtech-internship-tasks.git', 
                    credentialsId: 'github'
        }
      }
        stage('Setup Environment') {
            steps {
                script {
                    echo "Checking for Kind cluster..."
                    // This command checks if a cluster named 'kind' already exists
                    def clusterStatus = sh(script: "kind get clusters | grep -q '^kind$'", returnStatus: true)
                    
                    if (clusterStatus != 0) {
                        echo "Cluster not found. Creating Kind cluster..."
                        sh "kind create cluster --name kind"
                    } else {
                        echo "Kind cluster is already running. Proceeding..."
                    }
                }
            }
        }
       stage('Build Image') {
    steps {
        // -f tells docker exactly where the file is
        // the '.' at the end tells it to use the current folder as the "context"
        sh "docker build -t uniform-wala:local -f task3/Dockerfile task3/"
    }
}
        stage('Load into Kind') {
            steps {
                // This moves the image into the Kind cluster
                sh "kind load docker-image uniform-wala:local"
            }
        }
        stage('Deploy') {
            steps {
                sh "kubectl apply -f deployment.yaml"
                sh "kubectl apply -f service.yaml"
                sh "kubectl rollout status deployment/uniform-wala-app"
            }
        }
    }
}
