apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniform-wala-app
spec:
  # 1. Lower replicas to 1 for now to save space
  replicas: 1 
  selector:
    matchLabels:
      app: uniform-wala
  template:
    metadata:
      labels:
        app: uniform-wala
    spec:
      containers:
      - name: flask-container
        image: uniform-wala:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources:
          requests:
            # 2. Lower CPU from 500m to 100m (10% of a core)
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
