pipeline {
    agent any

    stages {
        stage('Cloning Repo') {
            steps {
                // Pulls the latest code from your internship repository
                git branch: 'master', url: 'https://github.com/kingpin1374/Codtech-internship-tasks.git'
            }
        }

        stage('Build & Load') {
            steps {
                // Build the image locally and load it into your Kind cluster
                sh "docker build -t uniform-wala:local -f task4/Dockerfile task4/"
                sh "kind load docker-image uniform-wala:local --name kind"
            }
        }

        stage('Deploy') {
            steps {
                dir('task3') {
                    // Apply manifests and wait for the app to be ready
                    sh 'kubectl apply -f deployment.yml'
                    sh 'kubectl apply -f service.yml'
                    sh 'kubectl rollout status deployment/uniform-wala-app'
                }
            }
        }
stage('OWASP ZAP Scan') {
            steps {
                script {
                    echo "Pulling ZAP image first to check space..."
                    sh "docker pull ghcr.io/zaproxy/zaproxy:stable"
                    
                    echo "Starting Dynamic Security Scan (DAST)..."
                    // We use --network=host to ensure it can see the KinD service on 8081
                    sh """
                    docker run --rm \
                        --network=host \
                        -v ${WORKSPACE}:/zap/wrk/:rw \
                        -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
                        -t http://127.0.0.1:8081 \
                        -r zap_report.html || true
                    """
                }
            }
        }

    post {
        always {
            echo "Pipeline finished. Saving the security report..."
            // This file is your main deliverable for the CODTECH task
            archiveArtifacts artifacts: 'zap_report.html', fingerprint: true
        }
    }
}
