pipeline{
  agent any

  environment{
    APP_NAME = 'webbook'
    APP_PORT = '9000'
  }

  triggers {
    githubPush()
  }
  stages{
    stage ('copy repo'){
      steps {
        git branch: 'master', url: 'https://github.com/kingpin1374/Codtech-internship-tasks.git', credentialsId: 'github'
      }
    }
stage('Setup & Install') {
    steps {
        sh '''
            # Create venv if it doesn't exist
            python3 -m venv venv
            
            # Use the venv pip to install everything
            ./venv/bin/pip install --upgrade pip
            ./venv/bin/pip install flask
            
            # Check if requirements.txt exists before installing
            if [ -f requirements.txt ]; then
                ./venv/bin/pip install -r requirements.txt
            fi
        '''
    }
}
    stage ('build and deploy') {
      steps {
        sh 'python3 app.py'
      }
    }
  }
  
}
