name: Task 2 - Deploy to EC2

on:
  push:
    branches: [ master ]
    paths:
      - 'task2/**'
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true
          script: |
            # Navigate to your project folder on EC2
            cd ~/Codtech-internship-tasks/task2
            
            # Pull the latest changes
            git pull origin master
            
            # Setup/Update Environment
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            
            # Restart the Flask App
            fuser -k 9000/tcp || true
            nohup python3 app.py > output.log 2>&1 &
            echo "Deployment successful on EC2!"
